// <auto-generated />
using System;
using Bookery.Node.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bookery.Node.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240310151238_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bookery.Node.Models.AccessType", b =>
                {
                    b.Property<int>("AccessTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AccessTypeId");

                    b.ToTable("AccessTypes");

                    b.HasData(
                        new
                        {
                            AccessTypeId = 0,
                            Name = "Read"
                        },
                        new
                        {
                            AccessTypeId = 1,
                            Name = "Write"
                        });
                });

            modelBuilder.Entity("Bookery.Node.Models.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<long>("CreationTimestamp")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDirectory")
                        .HasColumnType("boolean");

                    b.Property<long>("ModificationTimestamp")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ModifiedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentId");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("Bookery.Node.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Bookery.Node.Models.UserNode", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("AccessTypeId")
                        .HasColumnType("integer");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "NodeId");

                    b.HasIndex("AccessTypeId");

                    b.HasIndex("NodeId");

                    b.ToTable("UserNodes");
                });

            modelBuilder.Entity("Bookery.Node.Models.Node", b =>
                {
                    b.HasOne("Bookery.Node.Models.User", "CreatedBy")
                        .WithMany("CreatedNodes")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Bookery.Node.Models.User", "ModifiedBy")
                        .WithMany("ModifiedNodes")
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Bookery.Node.Models.User", "Owner")
                        .WithMany("OwnedNodes")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookery.Node.Models.Node", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Owner");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Bookery.Node.Models.UserNode", b =>
                {
                    b.HasOne("Bookery.Node.Models.AccessType", "AccessType")
                        .WithMany()
                        .HasForeignKey("AccessTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookery.Node.Models.Node", "Node")
                        .WithMany("UserNodes")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookery.Node.Models.User", "User")
                        .WithMany("UserNodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AccessType");

                    b.Navigation("Node");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bookery.Node.Models.Node", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("UserNodes");
                });

            modelBuilder.Entity("Bookery.Node.Models.User", b =>
                {
                    b.Navigation("CreatedNodes");

                    b.Navigation("ModifiedNodes");

                    b.Navigation("OwnedNodes");

                    b.Navigation("UserNodes");
                });
#pragma warning restore 612, 618
        }
    }
}
